### ISSUE TITLE
how to add new tools?

### ISSUE THREAD

**Issue by rik43** [advoor/nova-editor-js#19]
is it possible?

**Comment by nilsE** [comment]
would like to do that, too

**Comment by roelofr** [comment]
> Basic steps are really, add the new tool to the package.json, and then add the relevant config in FormField.vue.

Sadly this stops users from being able to fluently update their dependencies and add support for new fields. It would be awesome if some kind of hook-form could be worked out (maybe make the EditorJs macroable?)

I'll try to puzzle something together next week, because I too want to add a bunch of in-house tools.

**Comment by advoor** [comment]
@roelofr If you can, it would be awesome! I've not had any time at all recently to work on this, so any help is greatly appreciated!

**Comment by roelofr** [comment]
For now I figured out a possible way to solve this, but I'm absolutely not sure about this method, since it requires Javascript that changes stuff on the `window`.

However, as Nova doesn't re-compiles assets, I'm very afraid it's the only plausible method to use...
Look into #33 for more information, and please discuss the fix there.

**Comment by TheDeadCode** [comment]
See #41
